name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        pgver: [15, 14, 13, 12, 11]
        os: [ubuntu-latest, macos-latest]
        exclude:
          - os: macos-latest
            pgver: 14
          - os: macos-latest
            pgver: 13
          - os: macos-latest
            pgver: 12
          - os: macos-latest
            pgver: 11
      fail-fast: false
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: .pg
        key: ${{ matrix.os }}-pg-${{ matrix.pgver }}_V1

    - name: Configure
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: PGVER=${{ matrix.pgver }} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel --config ${{env.BUILD_TYPE}}

    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.2.6
      with:
        key: docker-${{ runner.os }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -timeout 1000 --force-new-ctest-process --verbose --output-on-failure -j $(nproc) -C ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ${{ matrix.os }}-${{ matrix.pgver }}-regression.diffs
        path: ${{ github.workspace }}/build/extensions/**/regression.diffs

    - name: Setup upterm session
      if: failure()
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        limit-access-to-users: yrashk



